from .densenet import *
from .efficientnet import *
from .kgcn import *
from .lenet import *
from .mlp import *
from .mobilenetv2 import *
from .moderate_cnns import *
from .regnet import *
from .resnet import *
from .resnet_evonorm import *
from .shufflenetv2 import *
from .simple_cnns import *
from .vgg import *
from .wideresnet import *
